### ISSUE TITLE
Clase de exceptii

### ISSUE THREAD

**Issue by catalinzz7** [catalinzz7/Web_Crawler#10]

**Comment by mateivladimir** [comment]
Am înțeles. Thank you mulțumesc merci. Trimis de pe telefonul meu Huawei-------- Mesaj original --------De la: catalinzz7 <notifications@github.com>Dată: joi, 10 dec. 2020, 10:51Către: catalinzz7/Web_Crawler <Web_Crawler@noreply.github.com>Cc: mateivladimir <mateivladimir23@gmail.com>, Assign <assign@noreply.github.com>Subiect: Re: [catalinzz7/Web_Crawler] Clase de exceptii (#10)
Assigned #10 to @mateivladimir.
